name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      working-directory: ./app
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew clean build
      
    - name: Unit tests
      working-directory: ./app
      run: ./gradlew test

    - name: Running Checkstyle
      working-directory: ./app
      run: ./gradlew checkstyle

    - name: Attach Checkstyle reports
      uses: actions/upload-artifact@v1
      with:
        name: Checkstyle-report
        path: /home/runner/work/new_test/new_test/app/app/build/reports/checkstyle/checkstyle.html
    
    - name: "Adding Checkstyle annotations"
      uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/checkstyle.xml'

    - name: Attach Lint reports
      uses: actions/upload-artifact@v1
      with:
        name: Lint-report
        path: /home/runner/work/new_test/new_test/app/app/build/reports/lint-results.html

    - name: Adding Lint annotations
      uses: yutailang0119/action-android-lint@v1.0.2
      with:
        xml_path: /home/runner/work/new_test/new_test/app/app/build/reports/lint-results.xml
