name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      working-directory: ./app
      run: chmod +x ./gradlew
      
    - name: See gradlew tasks
      working-directory: ./app
      run: ./gradlew tasks
      
    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew clean build
      
    - name: Unit tests
      working-directory: ./app
      run: ./gradlew test