name: Android CI

on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      working-directory: ./app
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew clean build
      
    - name: Unit tests
      working-directory: ./app
      run: ./gradlew test

    - name: Running Checkstyle
      working-directory: ./app
      run: ./gradlew checkstyle --stacktrace

    - name: Attach Checkstyle reports
      uses: actions/upload-artifact@v1
      with:
        name: Checkstyle-report
        path: /home/runner/work/buspal/buspal/app/app/build/reports/checkstyle/checkstyle.html
    
    - name: "Adding Checkstyle annotations"
      uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/checkstyle.xml'

    - name: Running Lint
      working-directory: ./app
      run: ./gradlew lint

    - name: Attach Lint reports
      uses: actions/upload-artifact@v1
      with:
        name: Lint-report
        path: /home/runner/work/buspal/buspal/app/app/build/reports/lint-results.html

    - name: Adding Lint annotations
      uses: yutailang0119/action-android-lint@v1.0.2
      with:
        xml_path: /home/runner/work/buspal/buspal/app/app/build/reports/lint-results.xml


    - name: Check Tag
      id: check-tag
      run: |
        echo ${{ github.ref }}
        if [[ ${{ github.ref }} =~ ^refs/tags/[v0-9.]*$ ]]; then
            echo ::set-output name=match::true
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        fi

    - uses: r0adkll/sign-android-release@v1
      name: Create signed APK
      if: steps.check-tag.outputs.match == 'true'
      id: sign_app
      with:
        releaseDirectory: app/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SHUSH_QUIET }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Create Release
      if: steps.check-tag.outputs.match == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.check-tag.outputs.SOURCE_TAG }}
        release_name: Release ${{ steps.check-tag.outputs.SOURCE_TAG }}
        body: |
          First release
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: steps.check-tag.outputs.match == 'true'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{steps.sign_app.outputs.signedReleaseFile}}
        asset_name: buspal.apk
        asset_content_type: application/zip